version: "3.4"
name: tourfrance-mariadb
services:
  mariadb:
    image: mariadb:11.2.6
    container_name: mariadb
    restart: always
    env_file: ./.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ CMD, healthckeck.sh, --connect, --innodb_initialized ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - network-tourfrance
  app:
    image: tourfrance
    container_name: myapi
    env_file: ./.env
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url" : "jdbc:mariadb://$MARIADB_HOST:$MARIADB_PORT/$MARIADB_DATABASE",
              "spring.datasource.username" : "$MARIADB_USERNAME",
              "spring.datasource.password" : "$MARIADB:PASSWORD",
              "spring.datasource.driverClassName" : "org.mariadb.jdbc.Driver",
              "spring.jpa.database-platform-dialect" : "org.hibernate.dialect.MariaDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update",
              "server.port" : 8080"
              }'
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    networks:
      - network-tourfrance
networks:
  network-tourfrance:
    driver: bridge

